### PR TITLE
Added support for asynchronous load so the extension will work in VS2019.

### PR DESCRIPTION
**Pull request by DJackman123**

### CODE REVIEW

**Comment by DJackman123** [comment]
Is this ever going to get merged?  It's been a year since I created the pull request.

**Comment by justcla** [comment]
Eek. I dunno. Sorry.

**Comment by tiesmaster** [comment]
@justcla The build was [failing back](https://github.com/justcla/HotCommands/issues/81#issuecomment-499074800) when this PR was created. I just looked into the build errors, and managed to get it fixed, but it requires quite a bit of work (see below).

Are you still interested in this contribution, and any future contributions? I'd love to get this fixed, and also a couple other improvements in mind. [I see](https://github.com/justcla/HotCommands/pull/82#issuecomment-614254558) you're not that enthusiastic, and saw that you changed positions to work on an IDE in another ecosystem, so I can imagine you don't want this to take too much of your time. So I want to make sure my time doesn't go to waste ;)

---

The way I fixed the  problem was by updating the target framework, and removed and added the assembly that was not getting resolved. I'm 100% sure the upgrading of the target framework is needed, so that requires a bit of investigation (or just taking the plump, and upgrade the framework).

**Comment by justcla** [comment]
Thanks. You're right, I don't have much time. But I care a lot about this one. Hot Commands is my baby. I'll definitely look at it within a week. Thanks!

**Comment by tiesmaster** [comment]
> Thanks. You're right, I don't have much time. But I care a lot about this one. Hot Commands is my baby.

❤️  Nice!

> I'll definitely look at it within a week. Thanks!

To make things clear, I _haven't_ put in a PR to fix the build. I need to figure out how to fix it _properly_, and I need your help for that ;)

I'll make a separate issue about this problem, so we can continue there, and get the build working.

**Comment by justcla** [comment]
Thanks. Maybe you can email me and we'll set up a time to work on it together.

**Comment by DJackman123** [comment]
I'm also happy to help out in any way I can.  Let me know.

**Comment by tiesmaster** [comment]
> Thanks. Maybe you can email me and we'll set up a time to work on it together.

Ah, very well. I didn't notice this message until just now, sorry about. I already looked into the build failure, and I think I have it fixed. If it doesn't then maybe it's indeed good to set apart some time, thanks for the offer! I couldn't find an email address of you, except an @microsoft one, so I'll contact you on Twitter ;)

**Comment by tiesmaster** [comment]
@justcla Turns out I can only DM you (duh), if you also follow me, then we can exchange contact information.

**Comment by justcla** [comment]
Build is no longer failing. Now builds in VS2015, VS2017 and VS2019.
Still has the deprecated APIs warning in VS2019.
Still warns about Synchronous loading.

**Comment by justcla** [comment]
@DJackman123  Many thanks for the code that you prepared well over a year ago.
Thanks for solving the Async issues for HotCommands.
I have pulled your code into the master branch and released it with HotCommands v3.0.0.

Thanks for your patience, and for your excellent contribution!

Long live Hot Commands!

**Pull request merged**
